### ISSUE TITLE
How to handle invisible column

### ISSUE THREAD

**Issue by prashantnirgun** [2ruslan/wrx#1]
Hi This is Prashant here let me thanks for creating such a powerfull utility. I was waiting for this. This is almost similar to dw2xls but Yet enhanced what I experience.

I had a computed column which i kept it in detail band but I dont want to display it so I overlap the detail band so it is not visible in datawindow / report preview. 

But if i exported my datawindow to excel through your utility it is occuping the row I try making it visible = false but didnt solve the purpose. If you can help me how to deal with following situation it will be the great help for me.
01 How to supress ie not want to shown in excel file what should i do?
02 I had put Line object and draw borders around the report and created a table kind of structure. how do I export this as it is to excel.

Note I put generate CSS property checked.

Thanks for creating such a wonderful library. If you don't permit ie with your permission can be put the powerbuilder community. I guess many of the developer desperatly searching for the pb 2 excel solution.

**Comment by 2ruslan** [comment]
Hi,
1. look n_cst_dw_unload.of_load_str_dw_cell . start with line  s = string( dw.Describe(ls_one_obj_dw +".visible"   ) ) 
2. lines are not supported, only the borders of objects. in lines was not necessary

I no longer work with PowerBuilder, this tool developed in 2005. If the library will be useful to someone would be pleased)
